### ISSUE TITLE
Daten Roaming

### ISSUE THREAD

**Issue by Henry2o1o** [berlinux2016/MIUI10#11]
TeleService.apk

- values-de, ist klar
- values-mcc234-mnc15  
-> values-mcc262-mnc2 für deutsch siehe unten
- values-mcc262-mnc4 
- values-mcc262-mnc9 

"roaming_enable">Data Roaming ermöglicht Ihnen das Surfen im Internet, die Nutzung von E-Mail, MMS und anderen Datendiensten im Ausland. Erkundigen Sie sich bei Ihrem Netzbetreiber nach den Preisen.

 "roaming_disable">Data Roaming ermöglicht Ihnen das Surfen im Internet, die Nutzung von E-Mail, MMS und anderen Datendiensten im Ausland. Erkundigen Sie sich bei Ihrem Netzbetreiber nach den Preisen.

 "roaming_warning">"Tippen Sie auf [OK], um Daten beim Roaming zu verwenden. Erkundigen Sie sich bei Ihrem Netzbetreiber nach den Preisen."

Wird dann auch in anderen Sprachen deutsch angezeigt.

**Comment by MeiGuddet** [comment]
Ich dachte, für die ROM's sind nur die deutschen strings im Ordner values-de relevant?

**Comment by Henry2o1o** [comment]
Habe ich gestern getestet. In der Pro haben sie die deut. Strings nicht eingefügt, dadurch bleibt es englisch. Dann habe ich den einen mnc2 geändert, schon ist es deut.
Stelle ich aber dann die Sprache um, bleibt es deut.

**Comment by MeiGuddet** [comment]
Dann nutzen die vielleicht die falschen strings?

**Comment by Henry2o1o** [comment]
Warum gibt es die Ordner nur hier?

**Comment by Henry2o1o** [comment]
http://mcc-mnc.com

**Comment by Henry2o1o** [comment]
@MeiGuddet 
Hat doch mit den -de Ordnern gar nichts zu tun.

**Comment by MeiGuddet** [comment]
Wenn die aber nicht für die deutsche Übersetzung in den ROM's gebraucht werden, sind sie doch irrelevant, oder?

**Comment by Henry2o1o** [comment]
![image](https://user-images.githubusercontent.com/6131799/42737637-11787350-8877-11e8-9158-d38dff736f7b.png)

**Comment by Henry2o1o** [comment]
Was heißt gebraucht werden, steht halt alles in englisch da.

**Comment by Henry2o1o** [comment]
gefolgt von dieser Seite

![image](https://user-images.githubusercontent.com/6131799/42737690-da191c24-8877-11e8-84e2-04ed09cccc73.png)

**Comment by Henry2o1o** [comment]
![image](https://user-images.githubusercontent.com/6131799/42737849-a35f69ac-8879-11e8-9e95-79904f93cf31.png)
