### ISSUE TITLE
SystemUI crashed alle paar Sekunden/Minuten seit 8.8.16

### ISSUE THREAD

**Issue by deepblue2000** [berlinux2016/MIUI10#14]
- **MIUI Version:** 8.8.16
- **Device name:** Mi 6

**Screenshot/Description:**
SystemUI crashed alle paar Sekunden/Minuten seite 8.8.16

Log: http://rgho.st/private/7k7pxmd2q/6cf25dee0d1ff02a9599691386f71c3c
Log2-3: http://rgho.st/private/8dbh7d89y/65ea3b13abb65392fb11f037363f0a92
Log4: http://rgho.st/private/7TQkwGGjt/f7d7d0d4f337656348fb9ae87c50dac6

**Comment by tt2g89** [comment]
Beim MI 8 dasselbe, wenn auf Englisch gestellt wird, stabilisiert es sich.

**Comment by Henry2o1o** [comment]
Bin gestern schon mal die letzten Änderungen durchgegangen, konnte bisher nich nichts finden.

**Comment by MeiGuddet** [comment]
Igor Eisberg/eu hat mir den Tipp gegeben, dass es hier dran hängen könnte:
[https://github.com/berlinux2016/MIUI10/commit/ce606e4151f15aef36011be8ac5ff5ea69271aeb](url)
Die Änderung hab  ich jetzt mal vorsichtshalber rückgängig gemacht.

**Comment by MeiGuddet** [comment]
Sorry, nochmal korrigiert, war nur eine Formatierung falsch, siehe [https://github.com/berlinux2016/MIUI10/commit/a866d46d280599d4c7fdff11eb6ff314c8eded48](url)

**Comment by Henry2o1o** [comment]
java.util.UnknownFormatConversionException: Conversion = 'M' at

**Comment by Henry2o1o** [comment]
Nach dem Umstellen von en nach de kam der gleiche Fehler wieder.

**Comment by MeiGuddet** [comment]
[https://xiaomi.eu/community/threads/8-8-16.45718/page-24#post-438824](url)
Mit 8.8.23 Fehler behoben.
