### ISSUE TITLE
Tag im Sperrbildschirm

### ISSUE THREAD

**Issue by darki15** [berlinux2016/MIUI10#15]
Mix 2, 8.8.23, Sperrbildschirm: Tag erscheint auf Englisch ("Friday").

**Comment by MeiGuddet** [comment]
Bisher noch nicht gefunden, woran es liegt, alles bisher gefundene ist auf Deutsch. Suche geht weiter.

**Comment by 6Mi6** [comment]
Ebenso in der Benachrichtigungsleiste.

![screenshot_2018-08-25-09-30-29-688_com yandex browser](https://user-images.githubusercontent.com/42691716/44616198-b0619980-a84b-11e8-828a-69682f405805.png)

**Comment by MeiGuddet** [comment]
@ScratchBuild @ingbrzy: Can any of you give me a clue where I can find this?

**Comment by Henry2o1o** [comment]
Ist das nur beim Mix 2?

**Comment by Henry2o1o** [comment]
Mix 2 und Mi6, wo noch?

**Comment by ingbrzy** [comment]
Not your issue.. German translation is removed from miui.apk to prevent system ui FC..

**Comment by Henry2o1o** [comment]
@ingbrzy
https://github.com/berlinux2016/MIUI10/commit/e28108184904ceb0da5d5209f9e7f7de200103b1

**Comment by MeiGuddet** [comment]
So finally fixed for next release.
