### ISSUE TITLE
use app Icons.....

### ISSUE THREAD

**Issue by 6Mi6** [berlinux2016/MIUI10#16]
- **MIUI Version:** X.X.X
- **Device name:** Mi XYZ

**Screenshot/Description:**

Miui Version 8.8.23
Xiaomi MI6

Use app Icons for notifications wurde nicht in übersetzt. 

![screenshot_2018-08-25-15-02-11-755_com android settings](https://user-images.githubusercontent.com/42691716/44618546-38f62f00-a878-11e8-9e9e-1f250411407a.png)

**Comment by MeiGuddet** [comment]
Schon bekannt, wurde auf xiaomi.eu gemeldet, wir kümmern uns drum.

**Comment by 6Mi6** [comment]
Bedanke mich!

**Comment by Henry2o1o** [comment]
https://github.com/berlinux2016/MIUI10/commit/15949528d96c794c7669f064a52e59f0c0ca1585#diff-b6ad3fee97fd5ce063e9ff8f57fbb444R5695

da war ich wohl etwas zu spät
