### ISSUE TITLE
First Aid komplett nicht übersetzt

### ISSUE THREAD

**Issue by PrinceXia1** [berlinux2016/MIUI10#18]
8.8.23
MI MIX

"Sicherheit"
Unterpunkt: First Aid mit Inhalt ist noch komplett auf Englisch

**Comment by WorXeN** [comment]
Ist bekannt und in der nächsten Version gefixed: https://github.com/berlinux2016/MIUI10/commit/81ac374dabfd15005ed6ffbd9aa80e03235cce92
