### ISSUE TITLE
Probleme - Übersetzung Miuisystemui.apk

### ISSUE THREAD

**Issue by Henry2o1o** [berlinux2016/MIUI10#2]
MIUI10 Oreo
Mi Mix - Lithium

![image](https://user-images.githubusercontent.com/6131799/41147597-1e9b7ce0-6b07-11e8-8734-e9d897436530.png)

**Comment by Henry2o1o** [comment]
Die Fehler wurden ja behoben?
Vielleicht ist die nächste ja in Ordnung.

Momentan läuft das System instabil und ein Neustart endet im Recovery.
Nach der Umstellung der Sprache ins Englische, läuft alles perfekt.

**Comment by berlinux2016** [comment]
Du nutzt auch MIUI 10 als testrom ?

Hen Ry <notifications@github.com> schrieb am Fr., 8. Juni 2018, 10:36:

**Comment by Henry2o1o** [comment]
Ja

**Comment by berlinux2016** [comment]
der tracelog ist von dir-vom jetzigen testgerät?

**Comment by Henry2o1o** [comment]
ja

<string name="velocity_tracker_impl"
<string name="quick_settings_tiles_default"
<string name="quick_settings_tiles_retail_mode"
<string name="quick_settings_tiles_stock"
<string name="quick_settings_tiles"

waren das Problem, diese wurden jetzt entfernt

**Comment by berlinux2016** [comment]
super
