### ISSUE TITLE
Einstellungen

### ISSUE THREAD

**Issue by freddiN** [berlinux2016/MIUI10#21]
- **MIUI Version:** MIUI 10 8.8.30
- **Device name:** Mi6

**Screenshot/Description:**
Einstellungen, Ton & Vibration, gaaanz unten: "Ton beim beim Löschen von Dateien".
Das "beim" ist doppelt.

![screenshot_2018-09-03-16-06-33-180_com android settings](https://user-images.githubusercontent.com/14030572/44991179-98002600-af93-11e8-84c7-84a8ced9a828.jpg)

Scheint in der MIUI10/German/main/Settings.apk/res/values-de/strings.xml zu sein, Zeile 1810:
`<string name="delete_sound_effect">Ton beim beim Löschen von Dateien</string>`

**Comment by Henry2o1o** [comment]
Danke, erledigt.
