### ISSUE TITLE
Einstellungen/Erweiterte Einstellungen/Sicherheit - Optischer Fehler

### ISSUE THREAD

**Issue by deepblue2000** [berlinux2016/MIUI10#25]
- **MIUI Version:** 8.10.25
- **Device name:** Mi 8

**Screenshot/Description:**
Einstellungen/Erweiterte Einstellungen/Sicherheit - Optischer Fehler bei "Standortzugriff"
da steht: "AN / %1$s"
![screenshot_2018-10-26-13-31-26-716_com android settings](https://user-images.githubusercontent.com/8377186/47563891-80a24100-d923-11e8-9e56-3ba245598bb6.png)

**Comment by MeiGuddet** [comment]
Wieder so ein string, der nur tlw. funktioniert, warum auch immer. In dipper, polaris, ursa heißt er so:
`<string name="location_on_summary">On</string>`
In allen anderen Geräten so:
`<string name="location_on_summary">ON / %1$s</string>`
Werde in an die neuen Geräte (wie dipper) anpassen.
