### ISSUE TITLE
MI Cloud backup funktioniert nicht

### ISSUE THREAD

**Issue by muugie** [berlinux2016/MIUI10#27]
- **MIUI Version:** 8.11.8
- **Device name:** Mi 8

**Screenshot/Description:** MI Cloud backup funktioniert nicht seit 26.10.18. Im Forum MI 8 berichten viele von diesem Bug

**Comment by MeiGuddet** [comment]
Und was hat das mit der deutschen Übersetzung zu tun?

**Comment by muugie** [comment]
Ok, es steht dort "report bugs". Ich wußte nicht, das hier nur bugs bezüglich der Übersetzung behandelt werden.

**Comment by MeiGuddet** [comment]
Nichts für ungut, aber es betrifft nur Bugs in der dt. Übersetzung. Mache dann jetzt hier zu.
