### ISSUE TITLE
\"%1$s\"

### ISSUE THREAD

**Issue by Henry2o1o** [berlinux2016/MIUI10#28]
`\"%1$s\" `
warum \ \ und " "

unterstrichen, blau und Anführungszeichen

![image](https://user-images.githubusercontent.com/6131799/49222131-5ab50400-f3db-11e8-85a5-0bb053ec2dc3.png)

![image](https://user-images.githubusercontent.com/6131799/49222139-5f79b800-f3db-11e8-995c-ed29d99e9b41.png)

**Comment by berlinux2016** [comment]
\ ist dass die Anführungszeichen dargestellt werden (xml code) - Die können aber weggelassen werden

**Comment by Henry2o1o** [comment]
> \ ist dass die Anführungszeichen dargestellt werden (xml code) - Die können aber weggelassen werden

Also auch beides, siehe 2. Screenshot?
