### ISSUE TITLE
Überflüssige strings in AuthManager.apk?

### ISSUE THREAD

**Issue by MeiGuddet** [berlinux2016/MIUI10#3]
In der AuthManager.apk gibt es ganz am Anfang strings, die mit **="Dashboard_** und mit **="Generic_** beginnen. Seit MIUI9 sind diese bei keinem Gerät mehr vorhanden, hat zumindest meine dateiübergreifende Suche mit Notepad++ ergeben. Werden die noch benötigt?

**Comment by berlinux2016** [comment]
nein können raus. einfach zum miui 10 repo vergleichen. es fliegt einiges raus.
