### ISSUE TITLE
Übersetzung unterschiedlich, Geräteabhängig

### ISSUE THREAD

**Issue by Henry2o1o** [berlinux2016/MIUI10#38]
Text (Connected %1$s) besteht aus String (Connected/Verbunden) und arrays (aktiv)
Jetzt könnte man nur Verbunden schreiben, dann passt das bei allen.

Vermutlich gibt es auch bei anderen Apps Übersetzungsprobleme.

`<string name="bluetooth_connected">Verbindung/Verbunden %1$s</string>`

```
<string-array name="bluetooth_audio_active_device_summaries">
<item>aktiv</item>
<item>aktiv (Medien)</item>
<item>aktiv (Telefon)</item> 
```

https://xiaomi.eu/community/threads/miui-10-neue-strings.44394/post-462590

https://xiaomi.eu/community/threads/miui-10-neue-strings.44394/post-460287

https://xiaomi.eu/community/threads/miui-10-neue-strings.44394/post-462485

![image](https://user-images.githubusercontent.com/6131799/50284239-bc0b4880-0458-11e9-8ef6-f2cba26d3d2e.png)

![image](https://user-images.githubusercontent.com/6131799/50284224-a7c74b80-0458-11e9-8f1c-fe56219193ad.png)

**Comment by Henry2o1o** [comment]
Ich der China Version (cn/en), gibt es nur Verbunden.

**Comment by berlinux2016** [comment]
einfach array raus nehmen - dann nur noch verbunden

**Comment by Henry2o1o** [comment]
Ist aber bei jedem Gerät anders, beim mir passt das perfekt.

**Comment by Henry2o1o** [comment]
Und kommt die Akkuanzeige des Bluetoothgeräes dazu, sieht das wieder ganz anders aus.

Und ein anderer/e String/s werden dafür genutzt.

**Comment by Henry2o1o** [comment]
Also müsste man die Geräte teilweise trennen?

**Comment by Henry2o1o** [comment]
![image](https://user-images.githubusercontent.com/6131799/51801397-4d7e8f00-223d-11e9-9f20-0990ae4ccab8.png)

**Comment by Henry2o1o** [comment]
Beispiel Teufel Boomster

![photo_2019-01-27_15-05-06](https://user-images.githubusercontent.com/6131799/51802006-92a6bf00-2245-11e9-873b-b6bbea9b7114.jpg)

mit Telefonanruf
![image](https://user-images.githubusercontent.com/6131799/51802031-c8e43e80-2245-11e9-8daf-5ab288a69054.png)

![photo_2019-01-27_15-05-14](https://user-images.githubusercontent.com/6131799/51802035-dc8fa500-2245-11e9-9f84-7c565b26a9fb.jpg)

**Comment by Henry2o1o** [comment]
### **Gerät Mi Max3 und BT-Lausprecher mit Akkuanzeig**e
- **mit und ohne Telefonanruf**
![photo_2019-01-27_15-55-03](https://user-images.githubusercontent.com/6131799/51802650-76f2e700-224c-11e9-9001-10079649ce83.jpg)

![photo_2019-01-27_15-54-53](https://user-images.githubusercontent.com/6131799/51802656-7eb28b80-224c-11e9-8aad-33fd1b22e847.jpg)

![photo_2019-01-27_15-54-49](https://user-images.githubusercontent.com/6131799/51802658-8114e580-224c-11e9-9cfa-092b570d7bd3.jpg)

![image](https://user-images.githubusercontent.com/6131799/51802673-9db11d80-224c-11e9-88bb-d8aad8388416.png)

**Comment by berlinux2016** [comment]
dann werden wir die Geräte trennen in dem bereich. folgt die nächsten tage

**Comment by Henry2o1o** [comment]
Ich schau mal in die ch. Strings, da sieht das etwas anders aus.

**Comment by Henry2o1o** [comment]
Moment noch, ich schau mal in die ch. Strings, da sieht das etwas anders aus.

Bei C..... gibt es auch für alle Geräte die gleichen Strings.

Ich passe mal die Strings an die Chinesischen an und wir schauen wie das das nächste mal aussieht.

**Comment by Henry2o1o** [comment]
So, fertig, mal sehen wie das jetzt aussieht.

**Comment by berlinux2016** [comment]
problem behoben?

**Comment by Henry2o1o** [comment]
sehe gerade ein update, 9.2.15, danach schaue ich mal

**Comment by Henry2o1o** [comment]
Mit dem Text scheint es wohl soweit zu stimmen, aber bei der Akkuanzeige eher nicht.

Momentan sehe ich das nur mit meinem Mix, das zeigt ja keinen Akku an, nur %1$s.
Ist vermutlich mit dem Mix nicht möglich. Beim Max 3 funktioniert es.

Würde man %1$s weglassen, dann wäre das für "ältere Geräte" ok, aber bei "Neueren" wird dann der Akku des BT-Gerätes nicht angezeigt.

**Comment by Henry2o1o** [comment]
Max 3

![photo_2019-02-18_12-40-59 2](https://user-images.githubusercontent.com/6131799/52948865-fa4eb680-337a-11e9-93da-d0afbafd6f8d.jpg)
![photo_2019-02-18_12-40-59 3](https://user-images.githubusercontent.com/6131799/52948866-fae74d00-337a-11e9-8cd0-980799171028.jpg)
![photo_2019-02-18_12-40-59 4](https://user-images.githubusercontent.com/6131799/52948867-fae74d00-337a-11e9-822c-955a0e45a92f.jpg)
![photo_2019-02-18_12-40-59](https://user-images.githubusercontent.com/6131799/52948869-fae74d00-337a-11e9-934b-48bb8ec7f6cb.jpg)

**Comment by Henry2o1o** [comment]
Mix - mit und ohne Telefonsignal

![photo_2019-02-18_12-47-38](https://user-images.githubusercontent.com/6131799/52949120-aabcba80-337b-11e9-8620-24c4ce448be8.jpg)
![photo_2019-02-18_12-47-39 2](https://user-images.githubusercontent.com/6131799/52949122-ab555100-337b-11e9-82e9-88627eccf32c.jpg)
![photo_2019-02-18_12-47-39 3](https://user-images.githubusercontent.com/6131799/52949123-ab555100-337b-11e9-951a-0bb49adac9ad.jpg)
![photo_2019-02-18_12-47-39](https://user-images.githubusercontent.com/6131799/52949124-ab555100-337b-11e9-98e8-d86daa19db8f.jpg)

**Comment by berlinux2016** [comment]
wir werden nicht in verschiedene Geräte splitten. Das gibt nur Chaos beim übersetzen. Zumal auch ältere Geräte nun auch Pie erhalten und damit das Problem erledigt ist. Die restlichen gehen immer mehr ins EOL.
