### ISSUE TITLE
items = Elemente

### ISSUE THREAD

**Issue by Henry2o1o** [berlinux2016/MIUI10#43]
items = Elemente finde ich etwas bescheiden

items würde ich genauer übersetzen

ich lösche ja keine/nicht nur Elemente, sondern Artikel , Dateien, Videos, Einträge, etc.

Beispiel: title_select_files -> Select items -> Elemente auswählen -> Dateien auswählen

**Comment by MeiGuddet** [comment]
Ich finde den allgemein gehaltenen Begriff 'Element/e' gut, weil er immer passt und eben nicht spezifiert. Sonst würde er in der englischen Übersetzung doch auch nicht für alles verwendet werden, dann würde dort der für den gerade vorkommenden Zusammenhang passende Begriff stehen. Bitte nicht ändern.

**Comment by Henry2o1o** [comment]
Ok
