### ISSUE TITLE
App Info

### ISSUE THREAD

**Issue by Brainbug01** [berlinux2016/MIUI10#45]
- **MIUI Version:** 9.3.21
- **Device name:** Mi Pad 4

Da steht: App-Bberechtigungen

Ist ein B zuviel

**Screenshot/Description:**
![Screenshot_2019-03-24-20-28-50-208_com android settings](https://user-images.githubusercontent.com/35106961/54884618-7dc85f80-4e73-11e9-91b1-fd3b43f62dbc.png)

**Comment by Henry2o1o** [comment]
Ok,  Danke
