### ISSUE TITLE
Settings.apk neu fehlende Menü Übersetzung

### ISSUE THREAD

**Issue by berlinux2016** [berlinux2016/MIUI10#46]
Übersetzungsfehler Settigns.apk (neu fehlender eintrag) in der heutigen ROM. Bitte mal jemand kurz nachsehen ob das wirklich an uns liegt, da ich momentan unterwegs bin. danke

But now there is a translation bug (german language)
"Benachrichtigungen & Statusleiste" Menu is now in english since 9.3.28
Confirming, didn't even notice earlier lol

**Comment by Henry2o1o** [comment]
Ja, das liegt an mir/uns. Ich habe die Strings, kam aber aus Zeitmangel noch nicht dazu. 
Bei Kamera und Settings fehlen noch ein Paar Strings.
Am WE ergänze ich diese noch, Sorry.

**Comment by MeiGuddet** [comment]
Soweit gefunden/möglich ergänzt.

**Comment by berlinux2016** [comment]
Super danke!
