### ISSUE TITLE
Unterschiede apk's in Xiaomi.eu-MIUIv10-XML-Compare zur MIUI10 hier

### ISSUE THREAD

**Issue by MeiGuddet** [berlinux2016/MIUI10#5]
Habe mal die bei uns gelisteten apk-Ordner mit den bis jetzt vorhandenen bei Xiaomi.eu verglichen. Da sind welche zuviel, andere fehlen, eine apk heißt anders. Vielleicht hab ich auch noch was übersehen.
--> Diese gibt es im englischen Compare-Verzeichnis nicht mehr:
BlockedNumberProvider.apk + BookmarkProvider.apk (beide hier nur strings.xml mit jeweils einem string name vorhanden).
CellBroadcastReceiver.apk
DocumentsUI.apk
EmergencyInfo.apk
FashionGallery.apk
KeyChain.apk
LiveWallpapersPicker.apk
Mipay.apk
MiPlay.apk
MiuiDaemon.apk
MiuiKeyguard.apk
MiuiPackageInstaller.apk
MtpDocumentsProvider.apk
Omacp.apk
SpacesPolicyApp.apk
YellowPage.apk
--> Andere apk-Bezeichnung: alt MiuiVideo.apk, neu MiuiVideoGlobal.apk
--> Diese apk-Verzeichnisse fehlen hier in der deutschen Übersetzung:
imssettings.apk > dipper, polaris, sagit, scorpio, whyred
NfcNci.apk >gemini, scorpio
NQNfcNci.apk > chiron, sagit, scorpio
MiuiExtraPhoto.apk > dipper
(Es gibt auch noch die PrintRecommendationService.apk, aber da ist nichts zu übersetzen.)
Sollen wir mal abwarten, ob andere Geräte die ganz oben genannten apk's noch bekommen? Oder löschen? Und kann ich die fehlenden apk-Ordner anlegen oder macht das einer von euch?

**Comment by berlinux2016** [comment]
super arbeit. kannst du die fehlenden apks ins repo einpflegen? bin gerade
beruflich unterwegs. whyred deckt schonmal alle neuen geräte ab.

Am Mo., 18. Juni 2018 um 22:26 Uhr schrieb MeiGuddet <
notifications@github.com>:

**Comment by MeiGuddet** [comment]
Kann ich machen. Jedenfalls kann ich es versuchen 😉

**Comment by MeiGuddet** [comment]
Sieht aus, als hätte es geklappt 😎

**Comment by berlinux2016** [comment]
super

**Comment by MeiGuddet** [comment]
Die o. g. apk, die im englischen Compare-Verzeichnis nicht mehr vorhanden sind, bleiben also hier im MIUI10 trotzdem drin?

**Comment by berlinux2016** [comment]
noch 2-4 wochen, dann kommen die raus. Die stören aber nicht, da die in den rom build nicht mit einfließen.

**Comment by MeiGuddet** [comment]
Ok, verstanden.
