### ISSUE TITLE
Xiaomi.eu MIUI 9.5.23 - AOD selection crashes with german language

### ISSUE THREAD

**Issue by deepblue2000** [berlinux2016/MIUI10#50]
- **MIUI Version:** 9.5.23
- **Device name:** Mi 8

**Screenshot/Description:**
AOD theme selection crashes when trying to open it, if Mi8 is set to german.
Umgebungsdisplay screen crashed, wenn man einen style auswählen will.
(funktioniert mit englischer sprache)

![Screenshot_2019-05-24-10-56-47-810_com miui bugreport](https://user-images.githubusercontent.com/8377186/58322066-2ec18b00-7e20-11e9-8a95-a6f49183709c.png)

**Comment by vcdwelt** [comment]
Same problem on my Phone. 
Also Mi8 (Dipper) and same Version (9.5.23).

Kann das Problem bestätigen. Wenn man das AOD Menü (Einstellungen -> Bildschirm -> Umgebungsdisplay) öffnet, kommt eine Absturzmeldung. Wenn man die Telefonsprache auf Englisch ändert, funktioniert es.
