### ISSUE TITLE
Miui 10.5_9.8.1german mi9 camera bug

### ISSUE THREAD

**Issue by 2mali** [berlinux2016/MIUI10#52]
- **MIUI Version:** 10.5, 9.8.1
- **Device name:** Mi 9

**Screenshot/Description:**
mi9 - camera app crash with german language. change to english - ok, switch back to german after reboot fails.

**Comment by ingbrzy** [comment]
Thanks @ScratchBuild 
9.8.1 will be rebuilt.. eh..

**Comment by ingbrzy** [comment]
@ScratchBuild this was an issue
https://github.com/berlinux2016/MIUI10/commit/c545278cb64e68aedc262addf40a2c0ec8f49ba7

**Comment by 2mali** [comment]
thank you both
