### ISSUE TITLE
Mi9Se Miui 10.5 xiaomi.eu 9.8.1 beta - Akkustatistik

### ISSUE THREAD

**Issue by nJoy-Android** [berlinux2016/MIUI10#54]
![Screenshot_2019-08-08-16-55-49-370_com miui securitycenter](https://user-images.githubusercontent.com/16748752/62714102-3562a600-b9fe-11e9-9d69-ed8e07f1cc23.jpg)
- **MIUI Version:** 10.5
- **Device name:** Mi 9Se

**Screenshot/Description:**

**Comment by nJoy-Android** [comment]
Seit dem letzten Ladevorgang
Verbleibend

**Comment by MeiGuddet** [comment]
Hab ich am 06.08. übersetzt, sollte jetzt alles drin sein.
@290fee34

**Comment by MeiGuddet** [comment]
Wenn nicht, einfach nochmals melden, wenn die neue ROM 9.8.8 installiert ist.
