### ISSUE TITLE
9.8.8 - Battery Statistics always crashing (Appname: Sicherheit)

### ISSUE THREAD

**Issue by moneymight** [berlinux2016/MIUI10#55]
- **MIUI Version:** 9.8.8
- **Device name:** Mi 9 SE (grus)

**Screenshot/Description:**
Hello Guys,

on the newly 9.8.8 the Battery-Statistics are always crashing.
I think it has something to do with the Translations.

Here is the Bugreport (as screenshot)

![image](https://user-images.githubusercontent.com/53931300/62759479-b3b45c00-ba81-11e9-8794-473befacec72.png)

Thanks for your work appreciate it.

Regards

**Comment by Henry2o1o** [comment]
`<string name="pc_statistics_battery_use_summary">% Sek seit letztem Laden</string`

`<string name="pc_statistics_battery_use_summary">%s since last charge</string>`

**Comment by Henry2o1o** [comment]
```xml
<string name="pc_statistics_battery_use_summary">%s seit letztem Laden</string>
```
