### ISSUE TITLE
Wecker bug

### ISSUE THREAD

**Issue by berlinux2016** [berlinux2016/MIUI10#7]
Wecker neu stellen mit Wiederholen Montag bis Freitag)

Nun erscheint Wecker klingelt in 2 Tage 21 stunden etc-Fehler=Tagen statt Tage

**Comment by berlinux2016** [comment]
fixed

**Comment by Henry2o1o** [comment]
Abkürzen, bei mir steht z.B. 2 Tage 16 St...

**Comment by berlinux2016** [comment]
grammatikalisch falsch- muss Wecker klingelt in xx Tagen heißen-ist schon geändert.

**Comment by Henry2o1o** [comment]
ich meinte die länge der übersetzung

**Comment by Henry2o1o** [comment]
ich sehe gerade minuten werden da gar nicht angezeigt

**Comment by Henry2o1o** [comment]
Mi Mix

**Comment by Henry2o1o** [comment]
![image](https://user-images.githubusercontent.com/6131799/41797749-81509856-766b-11e8-80cb-b3c120d5ea91.png)
![image](https://user-images.githubusercontent.com/6131799/41797754-85661d26-766b-11e8-8217-acdf641f84cc.png)

**Comment by berlinux2016** [comment]
Viel besser :)

Hen Ry <notifications@github.com> schrieb am Fr., 22. Juni 2018, 22:28:

**Comment by Henry2o1o** [comment]
![image](https://user-images.githubusercontent.com/6131799/41797971-4d007fca-766c-11e8-9c00-eb3d7a63463b.png)

**Comment by Henry2o1o** [comment]
sieht bescheiden aus

![image](https://user-images.githubusercontent.com/6131799/41798126-c39f9846-766c-11e8-80b5-7df6b6a0b34b.png)

**Comment by Henry2o1o** [comment]
Warum wir das nicht mehr ganz angezeigt , Abmessung?

**Comment by Henry2o1o** [comment]
WORAN LAG ES DENN?

**Comment by MeiGuddet** [comment]
Genau, möchte ich auch gern wissen, dann sind wir beim nächsten Mal vielleicht vorbereitet ;-)

**Comment by berlinux2016** [comment]
das hängt mit einigen bugs von android zusammen. die abmessungen ändern
sich ja gerade-aus 6zoll 16:9 wird bald 18:9 möglich sein usw. deshalb
passt xiaomi in den betas noch einiges an.

Also abwarten wird noch alles behoben

Am Fr., 22. Juni 2018 um 23:20 Uhr schrieb Hen Ry <notifications@github.com

**Comment by MeiGuddet** [comment]
Ich meine das mit dem Wecker. Du auch?

**Comment by berlinux2016** [comment]
nö-geht um die abmessungen. welches wecker problem?

Am So., 24. Juni 2018 um 08:57 Uhr schrieb MeiGuddet <
notifications@github.com>:

**Comment by MeiGuddet** [comment]
Na das mit der fehlenden Übersetzung?

**Comment by berlinux2016** [comment]
bin gerade nicht im bilde-was fehlt denn an übersetzung?

Am So., 24. Juni 2018 um 09:00 Uhr schrieb MeiGuddet <
notifications@github.com>:

**Comment by Henry2o1o** [comment]
Warum ist das immer noch so?

![image](https://user-images.githubusercontent.com/6131799/41867674-13bbc45a-78b4-11e8-862f-f663acbc4f0d.png)
